![](fig/logoENSI.png)
![](fig/logoPython.png)
 ***

# Introduction à la Programmation 
# Langage Python (cours 6)
***
**ENSICAEN  1A MC** 
vendredi 22 Nov 2019
## Eric Ziad-Forest
***

## Sommaire

- Modules
- Bibliothèques
    - Pylab
    - Scipy
    


***

**Auteur :**

- Eric Ziad-Forest ([ziad@ensicaen.fr](mailto: ziad@ensicaen.fr))
***
*Contenu sous licence [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0)*

# Scipy

In [30]:
%pylab

Using matplotlib backend: MacOSX
Populating the interactive namespace from numpy and matplotlib


/Users/ensicaen/anaconda/lib/python3.6/site-packages/IPython/core/magics/pylab.py:161: UserWarning: pylab import has clobbered these variables: ['linalg']
`%matplotlib` prevents importing * from pylab and numpy
  "\n`%matplotlib` prevents importing * from pylab and numpy"


In [2]:
import numpy as np

In [6]:
import scipy as sp

In [33]:
def maFonction(x): 
     return sin(x) 

In [34]:
from scipy import integrate

In [35]:
integrate.quad(maFonction,0,np.pi)

(2.0, 2.220446049250313e-14)

In [7]:
sp.sqrt(-1.0)

1j

In [37]:
type(sp.sqrt(-1.))

numpy.complex128

In [38]:
sp.finfo(np.float64).eps

2.2204460492503131e-16

On veux calculer:  $u = 100e^{{−100(x − 0.5)}^2}$ avec x ∈ [0, 1]

In [39]:
from numpy import *
x = linspace(0., 1., 100)
u = 100.*exp(-100.*(x - .5)**2)

In [40]:
type(x)

numpy.ndarray

In [41]:
u

array([  1.38879439e-09,   3.77474939e-09,   1.00525455e-08,
         2.62302071e-08,   6.70602464e-08,   1.67983382e-07,
         4.12292325e-07,   9.91475372e-07,   2.33612654e-06,
         5.39322510e-06,   1.21994003e-05,   2.70374774e-05,
         5.87126398e-05,   1.24920812e-04,   2.60420842e-04,
         5.31929936e-04,   1.06456180e-03,   2.08749322e-03,
         4.01067085e-03,   7.54999601e-03,   1.39256082e-02,
         2.51663004e-02,   4.45617596e-02,   7.73113109e-02,
         1.31420010e-01,   2.18885859e-01,   3.57200177e-01,
         5.71141054e-01,   8.94772943e-01,   1.37347279e+00,
         2.06568943e+00,   3.04402171e+00,   4.39509449e+00,
         6.21765240e+00,   8.61831599e+00,   1.17045882e+01,
         1.55749843e+01,   2.03065828e+01,   2.59408275e+01,
         3.24689734e+01,   3.98190635e+01,   4.78466215e+01,
         5.63312339e+01,   6.49807924e+01,   7.34443672e+01,
         8.13335512e+01,   8.82508158e+01,   9.38221701e+01,
         9.77304662e+01,

In [42]:
plot(x,u)


## Algebre linéaire -

In [43]:
from scipy import linalg

In [44]:
import scipy
scipy.ndarray is np.ndarray

True

In [45]:
arr = np.array([[1, 2],[3, 4]]);arr

array([[1, 2],
       [3, 4]])

In [46]:
linalg.det(arr)

-2.0

In [47]:
arr2 = np.array([[3, 2],[6, 4]]);arr2

array([[3, 2],
       [6, 4]])

In [48]:
iarr = linalg.inv(arr);iarr

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [49]:
dir(linalg)

['LinAlgError',
 'Tester',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_decomp_polar',
 '_decomp_qz',
 '_decomp_update',
 '_expm_frechet',
 '_fblas',
 '_flapack',
 '_flinalg',
 '_matfuncs_sqrtm',
 '_procrustes',
 '_solve_toeplitz',
 '_solvers',
 'absolute_import',
 'basic',
 'blas',
 'block_diag',
 'cho_factor',
 'cho_solve',
 'cho_solve_banded',
 'cholesky',
 'cholesky_banded',
 'circulant',
 'companion',
 'coshm',
 'cosm',
 'cython_blas',
 'cython_lapack',
 'decomp',
 'decomp_cholesky',
 'decomp_lu',
 'decomp_qr',
 'decomp_schur',
 'decomp_svd',
 'det',
 'dft',
 'diagsvd',
 'division',
 'eig',
 'eig_banded',
 'eigh',
 'eigvals',
 'eigvals_banded',
 'eigvalsh',
 'expm',
 'expm2',
 'expm3',
 'expm_cond',
 'expm_frechet',
 'find_best_blas_type',
 'flinalg',
 'fractional_matrix_power',
 'funm',
 'get_blas_funcs',
 'get_lapack_funcs',
 'hadamard',
 'hankel',
 'helmert',
 'hesse

In [50]:
iarr2 = linalg.inv(arr2);iarr2

LinAlgError: singular matrix

In [52]:
np.allclose(np.dot(arr, iarr), np.eye(2))

True

In [51]:
print(np.dot(arr, iarr))

[[  1.00000000e+00   0.00000000e+00]
 [  8.88178420e-16   1.00000000e+00]]


In [53]:
type(arr)

numpy.ndarray

In [55]:
ma=np.matrix(arr, copy=False)

In [54]:
type(ma)

module

In [56]:
ma[0,0]=9

In [57]:
ma

matrix([[9, 2],
        [3, 4]])

In [58]:
dir(matrix)

['A',
 'A1',
 'H',
 'I',
 'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dict__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmo

In [ ]:
arr

In [ ]:
type(arr)

In [59]:
arr*arr

array([[81,  4],
       [ 9, 16]])

In [60]:
print(np.dot(arr,arr))

[[87 26]
 [39 22]]


In [61]:
2*arr

array([[18,  4],
       [ 6,  8]])

In [62]:
arr*2  #attention mathématiquement pas correcte

array([[18,  4],
       [ 6,  8]])

In [ ]:
arr+arr

In [63]:
arr+1

array([[10,  3],
       [ 4,  5]])

In [64]:
print(np.dot(arr,arr2))

[[39 26]
 [33 22]]
